CongNgheWeb_3_0/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CongNgheWeb_3_0.Models;

namespace CongNgheWeb_3_0.Controllers
{
    public class AdminController : Controller
    {
        E_ClassEntities db = new E_ClassEntities();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
        //Get: list teacher
        public ActionResult ListTeacher()
        {
            var ListTeacher = db.tbl_User.Where(x=>x.Employee==true).ToList();
            return View(ListTeacher);
        }
    }
}

CongNgheWeb_3_0/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CongNgheWeb_3_0.Models;

namespace CongNgheWeb_3_0.Controllers
{
    public class CourseController : Controller
    {
        E_ClassEntities db = new E_ClassEntities();

        // GET: Course
        public ActionResult Index()
        {
            return View(db.tbl_Course.ToList());
        }

        // GET: Course/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Course/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Course/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Course/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Course/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Course/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Course/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CongNgheWeb_3_0/Views/Course/Create.cshtml
@model CongNgheWeb_3_0.Models.tbl_Course

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pirce, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pirce, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pirce, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalView, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalView, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalView, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalStudents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalStudents, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalStudents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Deleted)
                    @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.censored, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.censored)
                    @Html.ValidationMessageFor(model => model.censored, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CongNgheWeb_3_0/Views/Course/Index.cshtml
@model IEnumerable<CongNgheWeb_3_0.Models.tbl_Course>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- tables -->
<link href="~/Content/Admin/css/table-style.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="~/Content/Admin/css/basictable.css" />
<script type="text/javascript" src="~/Content/Admin/js/jquery.basictable.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#table').basictable();

        $('#table-breakpoint').basictable({
            breakpoint: 768
        });

        $('#table-swap-axis').basictable({
            swapAxis: true
        });

        $('#table-force-off').basictable({
            forceResponsive: false
        });

        $('#table-no-resize').basictable({
            noResize: true
        });

        $('#table-two-axis').basictable();

        $('#table-max-height').basictable({
            tableWrapper: true
        });
    });
</script>

<!--heder end here-->
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Admin")">Trang chủ</a></li>
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Course")">Các khóa học</a></li>
</ol>
<!--grid-->
<!-- //tables -->

<div class="agile-grids">
    <div class="agile-tables">

        <div class="w3l-table-info">
            <h2>Danh sách các khóa học</h2>
            <a class="btn btn-danger" href="@Url.Action("Create","Course")"><i class="fa fa-plus"></i> Thêm khóa học</a>
            <table id="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.CourseName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CourseImage)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Pirce)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Discount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TotalView)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TotalStudents)
                        </th>
                       
                        <th>
                            @Html.DisplayNameFor(model => model.tbl_Category.CategoryName)
                        </th>
                        <th width="10%">Chi tiết</th>
                        <th width="10%">Sửa</th>
                        <th width="10%">Xóa</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CourseName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CourseImage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Pirce)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Discount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalView)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalStudents)
                        </td>
                        
                        <td>
                            @Html.DisplayFor(modelItem => item.tbl_Category.CategoryName)
                        </td>

                        <td>
                            <a href="@Url.Action("Edit","Course",new {@id=item.ID})"><i class="fa fa-gear fa-1x"></i></a>
                        </td>
                        <td>
                            <a href="@Url.Action("Edit","Category",new {@id=item.ID})"><i class="fa fa-gear fa-1x"></i></a>
                        </td>
                        <td>
                            <a href="@Url.Action("Delete","Category",new {@id=item.ID}) "><i class="fa fa-times-circle-o fa-1x"></i></a>

                        </td>
                    </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>


</div>








<!--js -->
<script src="~/Content/Admin/js/jquery.nicescroll.js"></script>
<script src="~/Content/Admin/js/scripts.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="~/Content/Admin/js/bootstrap.min.js"></script>